name: wgeasyhost
services:
  wgeasyhost:
    container_name: wgeasyhost
    image: nginx:alpine
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 80
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - "apk update"
      - "apk add --no-cache wget"
      - "wget -O /etc/nginx/nginx.conf https://raw.githubusercontent.com/Worph/AppStore/main/Apps/WireGuardEasyHost/nginx.conf"
      - "nginx -g 'daemon off;'"
    depends_on:
      - wgeasyui

  wgeasyui:
    container_name: wgeasyui
    image: ghcr.io/wg-easy/wg-easy:13
    restart: unless-stopped
    network_mode: host
    environment:
      PASSWORD: '$default_pwd'
      WG_HOST: '$public_ip'
      WG_PORT: '51820'
      WG_DEFAULT_DNS: '9.9.9.9'
    x-casaos:
      volumes:
        - container: /etc/wireguard
          description:
            en_us: Contains device VPN config files.
      ports:
        - container: '51820'
          description:
            en_us: Wireguard VPN port
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/wireguard
        target: /etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  tagline:
    en_us: WEB UI to manage WireGuard VPN.
    zh_cn: 管理 WireGuard VPN 的 WEB UI。
    de_de: WEB UI zur Verwaltung von WireGuard VPN.
    es_es: WEB UI para gestionar WireGuard VPN.
    fr_fr: WEB UI pour gérer WireGuard VPN.
    hu_hu: WEB felhasználói felület a WireGuard VPN kezeléséhez.
    it_it: Interfaccia WEB per la gestione di WireGuard VPN.
    ru_ru: WEB-интерфейс для управления WireGuard VPN.
    pl_pl: WEB UI do zarządzania WireGuard VPN.
    pt_br: WEB UI para gerenciar o WireGuard VPN.
    sv_se: WEB UI för att hantera WireGuard VPN.
    uk_ua: WEB інтерфейс для керування WireGuard VPN.
  description:
    en_us: You have found the easiest way to install & manage WireGuard on any Linux host!
    zh_cn: 您已经找到了在任何 Linux 主机上安装和管理 WireGuard 的最简单方法！
    de_de: Sie haben den einfachsten Weg gefunden, WireGuard auf jedem Linux-Host zu installieren und zu verwalten!
    es_es: Ha encontrado la forma más sencilla de instalar y gestionar WireGuard en cualquier host Linux.
    fr_fr: Vous avez trouvé le moyen le plus simple d'installer et de gérer WireGuard sur n'importe quel hôte Linux !
    hu_hu: Megtalálta a WireGuard telepítésének és kezelésének legegyszerűbb módját bármely Linux hoszton!
    it_it: Avete trovato il modo più semplice per installare e gestire WireGuard su qualsiasi host Linux!
    ru_ru: Вы нашли самый простой способ установки и управления WireGuard на любом Linux-хосте!
    pl_pl: Znalazłeś najłatwiejszy sposób instalacji i zarządzania WireGuard na dowolnym hoście z systemem Linux!
    pt_br: Você encontrou a maneira mais fácil de instalar e gerenciar o WireGuard em qualquer host Linux!
    sv_se: Du har hittat det enklaste sättet att installera och hantera WireGuard på en Linux-värd!
    uk_ua: Ви знайшли найпростіший спосіб встановити WireGuard та керувати ним на будь-якому комп'ютері з Linux!
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Yundera/AppStoreLab@main/Apps/WireGuardEasyHost/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStoreLab@main/Apps/WireGuardEasyHost/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStoreLab@main/Apps/WireGuardEasyHost/screenshot-3.png
  developer: WeejeWel
  author: Sawy
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStoreLab@main/Apps/WireGuardEasyHost/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/Yundera/AppStoreLab@main/Apps/WireGuardEasyHost/icon.png
  category: Network
  title:
    en_us: WireGuard Easy - Host
  main: wgeasyh
  webui_port: 80
