# Nom du projet Docker Compose
name: pgadmin

services:
  # Service pour l'interface web pgAdmin
  pgadmin:
    # Image Docker officielle de pgAdmin4
    image: dpage/pgadmin4:latest
    # Nom du conteneur
    container_name: pgadmin
    # Redémarrage automatique sauf si arrêté manuellement
    restart: unless-stopped
    user: "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - /DATA/AppData/$AppID/pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      pcs: null

  # Service pour le serveur PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    # Variables d'environnement pour PostgreSQL
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - /DATA/AppData/$AppID/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    # Vérification de la santé du service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      pcs: null

# Définition du réseau partagé
networks:
  pcs:
    name: pcs

# Configuration spécifique à CasaOS
x-casaos:
  architectures:
    - amd64
    - arm64
  main: pgadmin
  author: UgEff
  category: Database
  description:
    en_us: A pre-configured package combining PostgreSQL database server and pgAdmin web interface. PostgreSQL is a powerful, open-source relational database, and pgAdmin is its official management tool. This package includes both services configured to work together out of the box.
  tagline:
    en_us: Ready-to-use PostgreSQL database with pgAdmin management interface
  title:
    en_us: PgAdmin + PostgreSQL
  icon: https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/PgAdmin_PostgreSQL/postgresql_icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/PgAdmin_PostgreSQL/screen1.png
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/PgAdmin_PostgreSQL/screen2.png
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/PgAdmin_PostgreSQL/screen3.png
  port_map: "8080"
  volumes:
    - container: /var/lib/pgadmin
      description: PgAdmin Data
    - container: /var/lib/postgresql/data
      description: PostgreSQL Data