name: jitsi

services:
  web:
    image: jitsi/web:stable
    container_name: jitsi-web
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - /DATA/AppData/$AppID/config:/config
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - DISABLE_HTTPS=1
      - PUBLIC_URL=https://${APP_URL}
      - ENABLE_XMPP_WEBSOCKET=0
      - ENABLE_IPV6=0
      - ENABLE_HTTP_REDIRECT=0
      - ENABLE_WELCOME_PAGE=1
      - ENABLE_CLOSE_PAGE=0
      - TZ=Europe/Paris
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
  main: web
  author: UgEff
  category: Communication
  description:
    en_us: Secure and simple video conferencing
  title:
    en_us: Jitsi Meet (Lite)
  port_map: "9000"
  volumes:
    - /DATA/AppData/$AppID/config
  icon: https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/JitsiMeet/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/JitsiMeet/screen1.png
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/JitsiMeet/screen2.png
    - https://raw.githubusercontent.com/UgEff/AppStore/BiApp/Apps/JitsiMeet/screen3.png
